// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MayanCalendar
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("gregorian")]
        public DateTimeOffset Gregorian { get; set; }

        [JsonProperty("longCount")]
        public LongCount LongCount { get; set; }

        [JsonProperty("tzolkin")]
        public Tzolkin Tzolkin { get; set; }

        [JsonProperty("haab")]
        public Haab Haab { get; set; }

        [JsonProperty("calendarRound")]
        public string CalendarRound { get; set; }

        [JsonProperty("daysSinceEpoch")]
        public long DaysSinceEpoch { get; set; }
    }

    public partial class Haab
    {
        [JsonProperty("day")]
        public long Day { get; set; }

        [JsonProperty("monthName")]
        public string MonthName { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }
    }

    public partial class LongCount
    {
        [JsonProperty("formatted")]
        public string Formatted { get; set; }

        [JsonProperty("baktun")]
        public long Baktun { get; set; }

        [JsonProperty("katun")]
        public long Katun { get; set; }

        [JsonProperty("tun")]
        public long Tun { get; set; }

        [JsonProperty("winal")]
        public long Winal { get; set; }

        [JsonProperty("kin")]
        public long Kin { get; set; }
    }

    public partial class Tzolkin
    {
        [JsonProperty("number")]
        public long Number { get; set; }

        [JsonProperty("dayName")]
        public string DayName { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }
    }
}
